export type PatientStatus = 'admitted' | 'discharged' | 'pending';

export interface Patient {
  id: string;
  name: string;
  gender: string;
  disease: string;
  room_id: string;
  room_number?: string;
  status: PatientStatus;
  admission_date: string;
  deposited_amount: number;
  pending_amount?: number;
  total_amount?: number;
  created_at?: string;
  updated_at?: string;
}

export interface PatientFormData {
  id?: string; // Optional since it will be generated by the backend
  name: string;
  gender: string;
  disease: string;
  room_id: string;
  deposited_amount: number;
  admission_date?: string;
  status?: string;
  pending_amount?: number;
  total_amount?: number;
  discharged_date?: string | null;
}

export interface Room {
  id: string;
  room_number: string;
  type: string;
  status: 'available' | 'occupied' | 'maintenance';
  floor?: string;
  rate_per_day?: number;
}

export interface PatientFilters {
  status?: PatientStatus;
  room_id?: string;
  search?: string;
}

export interface PatientStats {
  total: number;
  admitted: number;
  discharged: number;
  pending: number;
  total_revenue: number;
  pending_payments: number;
}
